# ref: https://jupyterbook.org/en/stable/customize/config.html
title: BoNesis documentation
author: Loïc Paulevé
copyright: "2023"
logo: logo.png

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: bonesis-doc.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/bnediction/bonesis-book  # Online location of your book
    #  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
