# ref: https://jupyterbook.org/en/stable/customize/config.html
title: "BoNesis: Synthesis and reprogramming of Boolean networks"
author: Loïc Paulevé
copyright: "2024"
logo: logo.png

bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/bnediction/bonesis  # Online location of your book
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: book

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  baseurl: "https://bnediction.github.io/bonesis/"

sphinx:
  config:
    language: en
      #    html_additional_pages:
      #test: custom.html

parse:
  myst_enable_extensions:
      # - amsmath
    - colon_fence
    - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist

# see https://jupyterbook.org/en/stable/content/execute.html
execute:
  stderr_output: remove
  # see https://jupyterbook.org/en/stable/content/execute.html#execute-cache
  execute_notebooks: cache
  #exclude_patterns:
    #    - 'tutorials/*'
