# ref: https://jupyterbook.org/en/stable/customize/config.html
title: "BoNesis: Synthesis and reprogramming of Boolean networks"
author: Loïc Paulevé
copyright: "2024"
logo: logo.png

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/bnediction/bonesis-book  # Online location of your book
    #  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true


sphinx:
  config:
    language: en
      #    html_additional_pages:
      #test: custom.html
