# ref: https://jupyterbook.org/en/stable/customize/config.html
title: "BoNesis: Synthesis and reprogramming of Boolean networks"
author: ""
logo: logo.png

bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/bnediction/bonesis  # Online location of your book
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: book

exclude_patterns : ['gallery/_notebooks', 'README.md']

html:
  baseurl: "https://bnediction.github.io/bonesis"
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  baseurl: "https://bnediction.github.io/bonesis/"
  extra_footer: |
    <p xmlns:cc="http://creativecommons.org/ns#" >This documentation is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></p>
    <p class="footer">
      Contact: <a href="https://loicpauleve.name">Loïc Paulevé</a>
      <br>
      <a href="https://www.labri.fr"><img class="logo logo-labri" src="https://bnediction.github.io/bonesis/_static/logo-labri.png" alt="LaBRI"></a>
      <img class="logo" src="https://bnediction.github.io/bonesis/_static/logo-cnrs.png" alt="CNRS">
      <img class="logo" src="https://bnediction.github.io/img/Logo-ANR-bleu-RVB.png" alt="ANR">
    </p>

sphinx:
  config:
    html_extra_path: ['_raw']
    language: en
      #    html_additional_pages:
      #test: custom.html
    html_show_copyright: false

parse:
  myst_enable_extensions:
      # - amsmath
    - attrs_inline
    - colon_fence
    - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist

# see https://jupyterbook.org/en/stable/content/execute.html
execute:
  stderr_output: remove
  # see https://jupyterbook.org/en/stable/content/execute.html#execute-cache
  execute_notebooks: cache
  #exclude_patterns:
    #    - 'tutorials/*'
